=== bhav0904/gs-xsd2bean/src/test/xsd/objectmanager.xsd
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
            jxb:version="1.0">
    <xsd:annotation>
        <xsd:documentation xml:lang="en">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
        </xsd:documentation>
        <xsd:appinfo>
            <jxb:globalBindings generateIsSetMethod="true"/>
        </xsd:appinfo>
    </xsd:annotation>

    <xsd:element name="TemplateList" type="TemplateType"/>

    <xsd:complexType name="TemplateType">
        <xsd:sequence>
            <xsd:element name="TemplateResource" type="TemplateResourceType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="TemplateResourceType">
        <xsd:attribute name="name" type="xsd:token" use="required"/>
        <xsd:attribute name="classPrefix" type="xsd:token"/>
        <xsd:attribute name="classSuffix" type="xsd:token"/>
        <xsd:attribute name="subPackage" type="xsd:token"/>
        <xsd:attribute name="dependentPackages" type="xsd:token"/>
        <xsd:attribute name="extension" type="xsd:token" use="required"/>
        <xsd:attribute name="default" type="xsd:boolean" default="false"/>
        <xsd:attribute name="group" type="xsd:token"/>
    </xsd:complexType>

    <xsd:element name="ManagedObject" type="ManagedObjectType"/>

    <xsd:complexType name="ManagedObjectType">
        <xsd:sequence>
            <xsd:element name="Templates" type="xsd:token" minOccurs="0"/>
            <xsd:element name="PackageName" type="xsd:token" minOccurs="1"/>
            <xsd:element name="ImportPackageName" type="xsd:token" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="ClassName" type="xsd:token" minOccurs="1"/>
            <xsd:element name="ImplementationClassName" type="xsd:token" minOccurs="0"/>
            <xsd:element name="SuperClassName" type="xsd:token" minOccurs="0"/>
            <xsd:element name="SuperInterfaceNames" type="xsd:token" minOccurs="0"/>
            <xsd:element name="ClassSerialVersionUID" type="xsd:token" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                    <xsd:documentation>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="InterfaceSerialVersionUID" type="xsd:token" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                    <xsd:documentation>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="AddCargo" type="xsd:boolean" minOccurs="0"/>
            <xsd:element name="Cacheable" type="xsd:boolean" minOccurs="0"/>
            <xsd:element name="CacheType" type="xsd:token" minOccurs="0"/>
            <xsd:element name="DefaultTable" type="xsd:token" minOccurs="0"/>
            <xsd:element name="SchemaName" type="xsd:token" minOccurs="0"/>
            <xsd:element name="DatabaseName" type="xsd:token" minOccurs="0"/>
            <xsd:element name="ConnectionManagerName" type="xsd:token" minOccurs="0"/>
            <xsd:element name="ReadOnly" type="xsd:boolean" minOccurs="0"/>
            <xsd:element name="ExplicitColumnNamesForSelect" type="xsd:boolean" minOccurs="0"/>
            <xsd:element name="Distinct" type="xsd:boolean" minOccurs="0"/>
            <xsd:element name="ReadStoredProcedure" type="xsd:token" minOccurs="0"/>
            <xsd:element name="InsertStoredProcedure" type="xsd:token" minOccurs="0"/>
            <xsd:element name="UpdateStoredProcedure" type="xsd:token" minOccurs="0"/>
            <xsd:element name="DeleteStoredProcedure" type="xsd:token" minOccurs="0"/>
            <xsd:element name="Faker" type="xsd:token" minOccurs="0"/>
            <xsd:element name="PrimaryKeyAttribute" type="PrimaryKeyType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="Attribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="BalanceAttribute" type="BalanceAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="BooleanAttribute" type="BooleanAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="ForeignKeyAttribute" type="ForeignKeyType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="ClassBasedAttribute" type="ClassBasedAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="TypeSafeEnumAttribute" type="TypeSafeEnumAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="Relationship" type="RelationshipType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="RelationshipBuilder" type="BuilderType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="AbstractMethod" type="AbstractMethodType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="Index" type="IndexType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="IndexBuilder" type="BuilderType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="SelectorIndex" type="xsd:token" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="AbstractAttributeType" abstract="true">
        <xsd:attribute name="name" type="xsd:token" use="required"/>
    </xsd:complexType>

    <!--<xsd:complexType name="AbstractSqlAttributeType" abstract="true">-->
    <!--<xsd:complexContent>-->
    <!--<xsd:extension base="AbstractAttributeType">-->
    <!--<xsd:attribute name="sqlType" type="xsd:token"/>-->
    <!--<xsd:attribute name="javaType" type="xsd:token"/>-->
    <!--<xsd:attribute name="columnName" type="xsd:token"/>-->
    <!--<xsd:anyAttribute namespace="##targetNamespace"/>-->
    <!--</xsd:extension>-->
    <!--</xsd:complexContent>-->
    <!--</xsd:complexType>-->

    <xsd:complexType name="AbstractClassType" abstract="true">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:sequence>
                    <xsd:element name="Attribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
                    <xsd:element name="BooleanAttribute" type="BooleanAttributeType" minOccurs="0" maxOccurs="unbounded"/>
                    <xsd:element name="ClassBasedAttribute" type="ClassBasedAttributeType" minOccurs="0" maxOccurs="unbounded"/>
                    <xsd:element name="TypeSafeEnumAttribute" type="TypeSafeEnumAttributeType" minOccurs="0"
                                 maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="AttributeType">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:attribute name="sqlType" type="xsd:token"/>
                <xsd:attribute name="javaType" type="xsd:token"/>
                <xsd:attribute name="columnName" type="xsd:token"/>
                <xsd:attribute name="maxLength" type="xsd:int"/>
                <xsd:attribute name="truncate" type="xsd:boolean" default="false"/>
                <xsd:attribute name="classBasedFieldName" type="xsd:token"/>
                <xsd:attribute name="nullable" type="xsd:boolean" default="true"/>
                <xsd:attribute name="poolable" type="xsd:boolean" default="true"/>
                <xsd:attribute name="defaultIfNull" type="xsd:token"/>
                <xsd:attribute name="trim" type="xsd:boolean" default="true"/>
                <xsd:attribute name="readonly" type="xsd:boolean" default="false"/>
                <xsd:attribute name="attributeFieldName" type="xsd:token" default=""/>
                <xsd:attribute name="interfaceOnly" type="xsd:boolean" default="false"/>
                <xsd:attribute name="value" type="xsd:token"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="BooleanAttributeType">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:attribute name="javaType" type="xsd:token" default="boolean"/>
                <xsd:attribute name="columnName" type="xsd:token" use="required"/>
                <xsd:attribute name="sqlType" type="xsd:token" use="required"/>
                <xsd:attribute name="trueValue" type="xsd:token"/>
                <xsd:attribute name="falseValue" type="xsd:token"/>
                <xsd:attribute name="defaultIfNull" type="xsd:token"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="BalanceAttributeType">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:attribute name="sqlType" type="xsd:token" use="required"/>
                <xsd:attribute name="columnName" type="xsd:token" use="required"/>
                <xsd:attribute name="inZMethodName" type="xsd:token" use="required"/>
                <xsd:attribute name="outZMethodName" type="xsd:token" use="required"/>
                <xsd:attribute name="javaType" type="xsd:token" default="double"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="AbstractMethodType">
        <xsd:attribute name="returnType" type="xsd:token" use="required"/>
        <xsd:attribute name="methodName" type="xsd:token" use="required"/>
        <xsd:attribute name="parameters" type="xsd:token"/>
    </xsd:complexType>

    <xsd:complexType name="PrimaryKeyType">
        <xsd:sequence>
            <xsd:element name="Attribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="BooleanAttribute" type="BooleanAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="ClassBasedAttribute" type="ClassBasedAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="TypeSafeEnumAttribute" type="TypeSafeEnumAttributeType" minOccurs="0"
                         maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="keyClass" type="xsd:token" use="optional"/>
        <xsd:attribute name="exposeAttributes" type="xsd:boolean" default="true"/>
    </xsd:complexType>

    <xsd:complexType name="ForeignKeyType">
        <xsd:complexContent>
            <xsd:extension base="AbstractClassType">
                <xsd:attribute name="keyClass" type="xsd:token" use="required"/>
                <xsd:attribute name="exposeAttributes" type="xsd:boolean" default="false"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="ClassBasedAttributeType">
        <xsd:complexContent>
            <xsd:extension base="AbstractClassType">
                <xsd:attribute name="attributeClass" type="xsd:token" use="required">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <!--
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                            -->
                            <jxb:property name="javaType"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="allowNulls" type="xsd:boolean" use="optional" default="true"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="TypeSafeEnumAttributeType">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:sequence>
                    <xsd:element name="Map" type="TypeSafeEnumMapType" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
                <xsd:attribute name="javaType" type="xsd:token" use="required"/>
                <xsd:attribute name="columnName" type="xsd:token" use="optional"/>
                <xsd:attribute name="sqlType" type="xsd:token" use="optional"/>
                <xsd:attribute name="lookupMethod" type="xsd:token" use="optional"/>
                <xsd:attribute name="value" type="xsd:token" use="optional"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="TypeSafeEnumMapType">
        <xsd:attribute name="constant" type="xsd:token" use="required"/>
        <xsd:attribute name="sqlValue" type="xsd:token" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="RelationshipType">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:attribute name="foreignKey" type="xsd:token"/>
                <xsd:attribute name="dependentClass" type="xsd:token" use="required"/>
                <xsd:attribute name="relationshipClass" type="xsd:token"/>
                <xsd:attribute name="cardinality" type="CardinalityType" use="required"/>
                <xsd:attribute name="dependentRelationshipAttribute" type="xsd:token"/>
                <xsd:attribute name="aggregation" type="xsd:boolean" default="false"/>
                <xsd:attribute name="useCacheIndexing" type="xsd:boolean" default="false"/>
                <xsd:attribute name="dynamic" type="xsd:boolean" default="false"/>
                <xsd:attribute name="interfaceOnly" type="xsd:boolean" default="false"/>
                <xsd:attribute name="deepSerialization" type="xsd:boolean" default="false"/>
                <xsd:attribute name="mandatory" type="xsd:boolean" default="false"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="IndexType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="xsd:token" use="required"/>
                <xsd:attribute name="unique" type="xsd:boolean" default="false"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="BuilderType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="className" type="xsd:token" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="SuperClassAttributeType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="xsd:token" use="required"/>
                <xsd:attribute name="generated" type="xsd:boolean"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="CardinalityType">
        <xsd:annotation>
            <xsd:appinfo>
                <jxb:typesafeEnumClass/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="one-to-many"/>
            <xsd:enumeration value="many-to-many"/>
            <xsd:enumeration value="many-to-many-key"/>
            <xsd:enumeration value="ordered-many-to-many"/>
            <xsd:enumeration value="one-to-one"/>
            <xsd:enumeration value="many-to-one"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="ObjectType">
        <xsd:annotation>
            <xsd:appinfo>
                <jxb:typesafeEnumClass/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="read-only"/>
            <xsd:enumeration value="transactional"/>
            <xsd:enumeration value="embedded-value"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="SuperClassType">
        <xsd:annotation>
            <xsd:appinfo>
                <jxb:typesafeEnumClass/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="table-per-subclass"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== bhav0904/gs-xsd2bean/src/test/testdata/fwcommon/objectmanager/TradeUnderlierLink.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<ManagedObject xsi:noNamespaceSchemaLocation="../../../xsd/objectmanager.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Templates>noki,wululu,nuzikuzu,key,tetahij</Templates>
    <PackageName>com.gs.fw.lilu.hos.domain.biziliniwof.zeqafopotu</PackageName>
    <ImportPackageName>com.gs.fw.lilu.wute.domain.yoru.Currency
    </ImportPackageName>
    <ImportPackageName>com.gs.fw.lilu.wute.domain.yoru.GifufekeZeb
    </ImportPackageName>
    <ImportPackageName>com.gs.fw.lilu.hos.domain.product.ZuquxuLOQOmawavi
    </ImportPackageName>
    <ClassName>YizihEkizaqediNodi</ClassName>
    <ConnectionManagerName/>
    <ReadOnly>true</ReadOnly>
    <ReadStoredProcedure>Qerat_WulUbiheTakevovamo</ReadStoredProcedure>

    <PrimaryKeyAttribute keyClass="HiqenUcokitedoBuxiHel">
        <Attribute columnName="JOVOY_P" javaType="long" sqlType="Nula"
                   name="sowiwEv"/>
        <Attribute columnName="QACEDIMI_PROD_RUM_YAK_P" javaType="int"
                   sqlType="Ciyisag" name="jusagofoGidogetAh"/>
        <Attribute columnName="BEFACEBAQ_PROD_RUM_YAK_P" javaType="int"
                   sqlType="Ciyisag" name="nigamucupOranemoVi"/>
        <Attribute columnName="businessDate" javaType="Timestamp"
                   sqlType="XIZofuxafasElegexaLimanigaw"
                   name="businessDate"/>
    </PrimaryKeyAttribute>

    <Attribute columnName="FAY_YAK_W" javaType="String" sqlType="XefeTewesa"
               name="ruwehuqiyOrejivata"/>
    <Attribute columnName="KAB_YAK_W" javaType="String" sqlType="XefeTewesa"
               name="huwAmayoduni"/>
    <Attribute columnName="COMPONENT_YAK_W" javaType="String"
               sqlType="XefeTewesa" name="dudawAfisorogiXum"/>
    <Attribute columnName="COMPONENT_NO_Z" javaType="Timestamp"
               sqlType="Timestamp" name="sihofOcerulofuJoQ"/>
    <Attribute columnName="PIXISEQAD_M" javaType="double" sqlType="Luhisa"
               name="pixiseqad"/>
    <Attribute columnName="FAY_XOV_ZOYOJO" javaType="double" sqlType="Luhisa"
               name="tinitiJuqux"/>
    <Attribute columnName="XUWIGA_FEZI_N" javaType="String" sqlType="XefeTewesa"
               name="giqeqeYici"/>

    <ForeignKeyAttribute keyClass="GifufekeZeb" name="xowicagalIqujEfoNit">
        <Attribute columnName="FAY_CIQ_N" javaType="String"
                   sqlType="HorupozoxObuhiriKoyedu" name="name"/>
        <Attribute columnName="businessDate" javaType="Timestamp"
                   sqlType="XIZofuxafasElegexaLimanigaw"
                   name="nuTeRogi"/>
    </ForeignKeyAttribute>

    <Relationship cardinality="many-to-one" dependentClass="Currency"
                  foreignKey="xowicagalIqujEfoNit"
                  name="manuremenUmobUmo" useCacheIndexing="true"/>
    <Relationship cardinality="many-to-one" dependentClass="ZuquxuLOQOmawavi"
                  foreignKey="wezurapuzIrocilaYos"
                  name="zupoyefudOsocucEvihici" useCacheIndexing="true"/>

    <AbstractMethod returnType="yuso" methodName="buxEjuyedomaLerazoxUta"
                    parameters="YowufarutaGib yowufarutaGib"/>
    <AbstractMethod returnType="YowufarutaGib"
                    methodName="fatAbuzacobeGatoboqIko"/>

    <AbstractMethod returnType="yuso" methodName="qenUxiwaMekeqofidOti"
                    parameters="YowufarutaGib yowufarutaGib"/>
    <AbstractMethod returnType="YowufarutaGib"
                    methodName="zoxAjumaWuxuyetuhEbi"/>

    <Index name="bogoxeWo">sowiwEv</Index>
    <Index name="businessDate">businessDate</Index>
    <Index name="miguhOhosoquniLax">miguhOhosoquniLax</Index>
</ManagedObject>

=== bhav0904/gs-xsd2bean/src/test/testdata/fwcommon/objectmanager/SecDbFuturePosition.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<ManagedObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../../../xsd/objectmanager.xsd">
    <Templates>interface,noki,nuzikuzu,wululu,tetahij,wunopi,riyoxadipojoxuj</Templates>
    <PackageName>com.gs.fw.lilu.hos.domain.biziliniwof</PackageName>
    <ImportPackageName>com.gs.fw.lilu.wute.domain.yoru.*</ImportPackageName>
    <ImportPackageName>com.gs.fw.lilu.wute.domain.jewivuy.*</ImportPackageName>
    <ImportPackageName>com.gs.fw.lilu.wute.domain.transaction.FixOtiz</ImportPackageName>

    <ClassName>PomInEpoyikObewafuc</ClassName>
    <DefaultTable>LOZUS_RAQEWO_MURELARUT</DefaultTable>
    <SchemaName>mut</SchemaName>
    <ReadOnly>true</ReadOnly>

    <PrimaryKeyAttribute keyClass="WuvEzAjulujOlohiqerUfa">
        <Attribute columnName="XEL" javaType="String" name="sowiwEv"
                   sqlType="XefeTewesa"/>
        <Attribute columnName="RAQEWO_TADE_N" javaType="String" name="yarItag"
                   sqlType="XefeTewesa"/>
        <Attribute columnName="businessDate" javaType="Timestamp"
                   name="businessDate"
                   sqlType="XIZofuxafasElegexaLimanigaw"/>
    </PrimaryKeyAttribute>

    <Attribute columnName="LEREQ_TADE_N" javaType="String" name="tezexUxiw"
               sqlType="XefeTewesa"/>
    <Attribute columnName="CICAVIDO_M" javaType="double" name="cicavido"
               sqlType="Luhisa"/>

    <Attribute columnName="HETIKE_SIBA" javaType="Timestamp" name="yuhisiTadi"
               sqlType="Timestamp"/>
    <Attribute columnName="XEJOFIHA_SIBA_Z" javaType="Timestamp"
               name="yelacopoVeda" sqlType="Timestamp"/>
    <Attribute columnName="JEHECU_DAFUZ_M" javaType="double" name="widazoXific"
               sqlType="Luhisa"/>
    <Attribute columnName="CIQAKANI_FACTOR_M" javaType="double"
               name="yeqeyixaRituyo" sqlType="Luhisa"/>
    <Attribute columnName="RUC_Z" javaType="Timestamp" name="fosawIv"
               sqlType="BimowupuyEyowubesa"/>

    <ForeignKeyAttribute name="mefunakOle" keyClass="MefunakOle">
        <Attribute columnName="DOMU_W" javaType="String" name="cejasawUwesij"
                   sqlType="XefeTewesa"/>
        <Attribute columnName="businessDate" javaType="Timestamp"
                   name="businessDate"
                   sqlType="XIZofuxafasElegexaLimanigaw"/>
    </ForeignKeyAttribute>

    <ForeignKeyAttribute name="dezoseMosoJukizicuHil" keyClass="GifufekeZeb">
        <Attribute javaType="String" name="name" columnName="HOJI_CIQ"
                   sqlType="XefeTewesa"/>
        <Attribute javaType="Timestamp" name="businessDate"
                   columnName="businessDate"
                   sqlType="XIZofuxafasElegexaLimanigaw"/>
    </ForeignKeyAttribute>

    <TypeSafeEnumAttribute name="fixOtiz" javaType="FixOtiz" columnName="JOP_VUCI_N"
                           sqlType="XefeTewesa" lookupMethod="gamEhajoqol"/>

    <Relationship cardinality="many-to-one" dependentClass="PajaVopakey"
                  foreignKey="mefunakOle" name="jewivuy"/>
    <Relationship cardinality="many-to-one" dependentClass="Currency"
                  foreignKey="dezoseMosoJukizicuHil"
                  name="naxajuQoroFuxebovi"/>

    <Index name="businessDate">businessDate</Index>
</ManagedObject>

=== bhav0904/gs-xsd2bean/src/test/testdata/fwcommon/objectmanager/SecDbSwapLeg.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<ManagedObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../../../xsd/objectmanager.xsd">
    <Templates>javeneruma,interface,noki,nuzikuzu,wululu,tetahij,riyoxadipojoxuj,wunopi</Templates>
    <PackageName>com.gs.fw.lilu.hos.domain.biziliniwof</PackageName>
    <ImportPackageName>com.gs.fw.lilu.wute.domain.yoru.*</ImportPackageName>

    <ClassName>QagOjAhejEgo</ClassName>
    <DefaultTable>LOZUS_NIDA_CEPO</DefaultTable>
    <SchemaName>mut</SchemaName>
    <ReadOnly>true</ReadOnly>

    <PrimaryKeyAttribute keyClass="SomIrIdujOhoHom">
        <Attribute columnName="NIDA_FEVEGOGA_P" javaType="long"
                   name="zaziRototucoFa" sqlType="Nula"/>
        <Attribute columnName="businessDate" javaType="Timestamp"
                   name="businessDate"
                   sqlType="XIZofuxafasElegexaLimanigaw"/>
        <Attribute columnName="KAB_TADE_N" javaType="String"
                   name="yarItag"
                   sqlType="XefeTewesa"/>
    </PrimaryKeyAttribute>

    <Attribute columnName="JEWIVUY_W" javaType="String" name="cejasawUwesij"
               sqlType="XefeTewesa"/>
    <Attribute columnName="TAZA_YAK_W" javaType="String" name="vicuLoj"
               sqlType="XefeTewesa"/>
    <Attribute columnName="LEREQ_TADE_N" javaType="String" name="tezexUxiw"
               sqlType="XefeTewesa"/>
    <Attribute columnName="NILI_M" javaType="double" name="pegukeGile"
               sqlType="Luhisa"/>
    <Attribute columnName="SAK_M" javaType="double" name="lezUtoga"
               sqlType="Luhisa"/>
    <Attribute columnName="CICAVIDO_M" javaType="double" name="hovarimiBepib"
               sqlType="Luhisa"/>
    <Attribute columnName="HETIKE_SIBA_Z" javaType="Timestamp" name="yuhisiTadi"
               sqlType="Timestamp"/>
    <Attribute columnName="POGIRO_SIBA_Z" javaType="Timestamp" name="rexoviCita"
               sqlType="Timestamp"/>
    <Attribute columnName="XEJOFIHA_SIBA_Z" javaType="Timestamp"
               name="yelacopoVeda" sqlType="Timestamp"/>
    <Attribute columnName="RUC_Z" javaType="Timestamp" name="fosawIv"
               sqlType="BimowupuyEyowubesa"/>
    <Attribute columnName="DILEWERI_N" javaType="String" name="dileweri"
               sqlType="XefeTewesa"/>
    <Attribute columnName="KOZETOTE_SIGOVIBI_M" javaType="double" name="wusuminaKowepobe"
               sqlType="Luhisa"/>
    <Attribute columnName="LOZUS_BO01" javaType="double" name="debIpUq01"
               sqlType="Luhisa"/>
    <Attribute columnName="GIFAX_M" javaType="double" name="gifax"
               sqlType="Luhisa"/>
    <Attribute columnName="DUQEQI_SAK_M" javaType="double" name="funoloSixItofi"
               sqlType="Luhisa"/>
    <Attribute columnName="NEMADO_N" javaType="int"
                   name="bufuzuKove" sqlType="Ciyisag"/>

    <Index name="businessDate">businessDate</Index>
</ManagedObject>
