=== bhav0904/gs-xsd2bean/src/test/xsd/objectmanager.xsd
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
            jxb:version="1.0">
    <xsd:annotation>
        <xsd:documentation xml:lang="en">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
        </xsd:documentation>
        <xsd:appinfo>
            <jxb:globalBindings generateIsSetMethod="true"/>
        </xsd:appinfo>
    </xsd:annotation>

    <xsd:element name="TemplateList" type="TemplateType"/>

    <xsd:complexType name="TemplateType">
        <xsd:sequence>
            <xsd:element name="TemplateResource" type="TemplateResourceType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="TemplateResourceType">
        <xsd:attribute name="name" type="xsd:token" use="required"/>
        <xsd:attribute name="classPrefix" type="xsd:token"/>
        <xsd:attribute name="classSuffix" type="xsd:token"/>
        <xsd:attribute name="subPackage" type="xsd:token"/>
        <xsd:attribute name="dependentPackages" type="xsd:token"/>
        <xsd:attribute name="extension" type="xsd:token" use="required"/>
        <xsd:attribute name="default" type="xsd:boolean" default="false"/>
        <xsd:attribute name="group" type="xsd:token"/>
    </xsd:complexType>

    <xsd:element name="ManagedObject" type="ManagedObjectType"/>

    <xsd:complexType name="ManagedObjectType">
        <xsd:sequence>
            <xsd:element name="Templates" type="xsd:token" minOccurs="0"/>
            <xsd:element name="PackageName" type="xsd:token" minOccurs="1"/>
            <xsd:element name="ImportPackageName" type="xsd:token" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="ClassName" type="xsd:token" minOccurs="1"/>
            <xsd:element name="ImplementationClassName" type="xsd:token" minOccurs="0"/>
            <xsd:element name="SuperClassName" type="xsd:token" minOccurs="0"/>
            <xsd:element name="SuperInterfaceNames" type="xsd:token" minOccurs="0"/>
            <xsd:element name="ClassSerialVersionUID" type="xsd:token" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                    <xsd:documentation>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="InterfaceSerialVersionUID" type="xsd:token" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                    <xsd:documentation>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="AddCargo" type="xsd:boolean" minOccurs="0"/>
            <xsd:element name="Cacheable" type="xsd:boolean" minOccurs="0"/>
            <xsd:element name="CacheType" type="xsd:token" minOccurs="0"/>
            <xsd:element name="DefaultTable" type="xsd:token" minOccurs="0"/>
            <xsd:element name="SchemaName" type="xsd:token" minOccurs="0"/>
            <xsd:element name="DatabaseName" type="xsd:token" minOccurs="0"/>
            <xsd:element name="ConnectionManagerName" type="xsd:token" minOccurs="0"/>
            <xsd:element name="ReadOnly" type="xsd:boolean" minOccurs="0"/>
            <xsd:element name="ExplicitColumnNamesForSelect" type="xsd:boolean" minOccurs="0"/>
            <xsd:element name="Distinct" type="xsd:boolean" minOccurs="0"/>
            <xsd:element name="ReadStoredProcedure" type="xsd:token" minOccurs="0"/>
            <xsd:element name="InsertStoredProcedure" type="xsd:token" minOccurs="0"/>
            <xsd:element name="UpdateStoredProcedure" type="xsd:token" minOccurs="0"/>
            <xsd:element name="DeleteStoredProcedure" type="xsd:token" minOccurs="0"/>
            <xsd:element name="Faker" type="xsd:token" minOccurs="0"/>
            <xsd:element name="PrimaryKeyAttribute" type="PrimaryKeyType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="Attribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="BalanceAttribute" type="BalanceAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="BooleanAttribute" type="BooleanAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="ForeignKeyAttribute" type="ForeignKeyType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="ClassBasedAttribute" type="ClassBasedAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="TypeSafeEnumAttribute" type="TypeSafeEnumAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="Relationship" type="RelationshipType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="RelationshipBuilder" type="BuilderType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="AbstractMethod" type="AbstractMethodType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="Index" type="IndexType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="IndexBuilder" type="BuilderType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="SelectorIndex" type="xsd:token" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="AbstractAttributeType" abstract="true">
        <xsd:attribute name="name" type="xsd:token" use="required"/>
    </xsd:complexType>

    <!--<xsd:complexType name="AbstractSqlAttributeType" abstract="true">-->
    <!--<xsd:complexContent>-->
    <!--<xsd:extension base="AbstractAttributeType">-->
    <!--<xsd:attribute name="sqlType" type="xsd:token"/>-->
    <!--<xsd:attribute name="javaType" type="xsd:token"/>-->
    <!--<xsd:attribute name="columnName" type="xsd:token"/>-->
    <!--<xsd:anyAttribute namespace="##targetNamespace"/>-->
    <!--</xsd:extension>-->
    <!--</xsd:complexContent>-->
    <!--</xsd:complexType>-->

    <xsd:complexType name="AbstractClassType" abstract="true">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:sequence>
                    <xsd:element name="Attribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
                    <xsd:element name="BooleanAttribute" type="BooleanAttributeType" minOccurs="0" maxOccurs="unbounded"/>
                    <xsd:element name="ClassBasedAttribute" type="ClassBasedAttributeType" minOccurs="0" maxOccurs="unbounded"/>
                    <xsd:element name="TypeSafeEnumAttribute" type="TypeSafeEnumAttributeType" minOccurs="0"
                                 maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="AttributeType">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:attribute name="sqlType" type="xsd:token"/>
                <xsd:attribute name="javaType" type="xsd:token"/>
                <xsd:attribute name="columnName" type="xsd:token"/>
                <xsd:attribute name="maxLength" type="xsd:int"/>
                <xsd:attribute name="truncate" type="xsd:boolean" default="false"/>
                <xsd:attribute name="classBasedFieldName" type="xsd:token"/>
                <xsd:attribute name="nullable" type="xsd:boolean" default="true"/>
                <xsd:attribute name="poolable" type="xsd:boolean" default="true"/>
                <xsd:attribute name="defaultIfNull" type="xsd:token"/>
                <xsd:attribute name="trim" type="xsd:boolean" default="true"/>
                <xsd:attribute name="readonly" type="xsd:boolean" default="false"/>
                <xsd:attribute name="attributeFieldName" type="xsd:token" default=""/>
                <xsd:attribute name="interfaceOnly" type="xsd:boolean" default="false"/>
                <xsd:attribute name="value" type="xsd:token"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="BooleanAttributeType">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:attribute name="javaType" type="xsd:token" default="boolean"/>
                <xsd:attribute name="columnName" type="xsd:token" use="required"/>
                <xsd:attribute name="sqlType" type="xsd:token" use="required"/>
                <xsd:attribute name="trueValue" type="xsd:token"/>
                <xsd:attribute name="falseValue" type="xsd:token"/>
                <xsd:attribute name="defaultIfNull" type="xsd:token"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="BalanceAttributeType">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:attribute name="sqlType" type="xsd:token" use="required"/>
                <xsd:attribute name="columnName" type="xsd:token" use="required"/>
                <xsd:attribute name="inZMethodName" type="xsd:token" use="required"/>
                <xsd:attribute name="outZMethodName" type="xsd:token" use="required"/>
                <xsd:attribute name="javaType" type="xsd:token" default="double"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="AbstractMethodType">
        <xsd:attribute name="returnType" type="xsd:token" use="required"/>
        <xsd:attribute name="methodName" type="xsd:token" use="required"/>
        <xsd:attribute name="parameters" type="xsd:token"/>
    </xsd:complexType>

    <xsd:complexType name="PrimaryKeyType">
        <xsd:sequence>
            <xsd:element name="Attribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="BooleanAttribute" type="BooleanAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="ClassBasedAttribute" type="ClassBasedAttributeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="TypeSafeEnumAttribute" type="TypeSafeEnumAttributeType" minOccurs="0"
                         maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="keyClass" type="xsd:token" use="optional"/>
        <xsd:attribute name="exposeAttributes" type="xsd:boolean" default="true"/>
    </xsd:complexType>

    <xsd:complexType name="ForeignKeyType">
        <xsd:complexContent>
            <xsd:extension base="AbstractClassType">
                <xsd:attribute name="keyClass" type="xsd:token" use="required"/>
                <xsd:attribute name="exposeAttributes" type="xsd:boolean" default="false"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="ClassBasedAttributeType">
        <xsd:complexContent>
            <xsd:extension base="AbstractClassType">
                <xsd:attribute name="attributeClass" type="xsd:token" use="required">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <!--
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                            -->
                            <jxb:property name="javaType"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="allowNulls" type="xsd:boolean" use="optional" default="true"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="TypeSafeEnumAttributeType">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:sequence>
                    <xsd:element name="Map" type="TypeSafeEnumMapType" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
                <xsd:attribute name="javaType" type="xsd:token" use="required"/>
                <xsd:attribute name="columnName" type="xsd:token" use="optional"/>
                <xsd:attribute name="sqlType" type="xsd:token" use="optional"/>
                <xsd:attribute name="lookupMethod" type="xsd:token" use="optional"/>
                <xsd:attribute name="value" type="xsd:token" use="optional"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="TypeSafeEnumMapType">
        <xsd:attribute name="constant" type="xsd:token" use="required"/>
        <xsd:attribute name="sqlValue" type="xsd:token" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="RelationshipType">
        <xsd:complexContent>
            <xsd:extension base="AbstractAttributeType">
                <xsd:attribute name="foreignKey" type="xsd:token"/>
                <xsd:attribute name="dependentClass" type="xsd:token" use="required"/>
                <xsd:attribute name="relationshipClass" type="xsd:token"/>
                <xsd:attribute name="cardinality" type="CardinalityType" use="required"/>
                <xsd:attribute name="dependentRelationshipAttribute" type="xsd:token"/>
                <xsd:attribute name="aggregation" type="xsd:boolean" default="false"/>
                <xsd:attribute name="useCacheIndexing" type="xsd:boolean" default="false"/>
                <xsd:attribute name="dynamic" type="xsd:boolean" default="false"/>
                <xsd:attribute name="interfaceOnly" type="xsd:boolean" default="false"/>
                <xsd:attribute name="deepSerialization" type="xsd:boolean" default="false"/>
                <xsd:attribute name="mandatory" type="xsd:boolean" default="false"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="IndexType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="xsd:token" use="required"/>
                <xsd:attribute name="unique" type="xsd:boolean" default="false"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="BuilderType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="className" type="xsd:token" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="SuperClassAttributeType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="xsd:token" use="required"/>
                <xsd:attribute name="generated" type="xsd:boolean"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="CardinalityType">
        <xsd:annotation>
            <xsd:appinfo>
                <jxb:typesafeEnumClass/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="one-to-many"/>
            <xsd:enumeration value="many-to-many"/>
            <xsd:enumeration value="many-to-many-key"/>
            <xsd:enumeration value="ordered-many-to-many"/>
            <xsd:enumeration value="one-to-one"/>
            <xsd:enumeration value="many-to-one"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="ObjectType">
        <xsd:annotation>
            <xsd:appinfo>
                <jxb:typesafeEnumClass/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="read-only"/>
            <xsd:enumeration value="transactional"/>
            <xsd:enumeration value="embedded-value"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="SuperClassType">
        <xsd:annotation>
            <xsd:appinfo>
                <jxb:typesafeEnumClass/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="table-per-subclass"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== bhav0904/gs-xsd2bean/src/test/testdata/fwcommon/objectmanager/ContractualDetail.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<ManagedObject xsi:noNamespaceSchemaLocation="../../../xsd/objectmanager.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Templates>interface,noki,wunopi,tetahij,key,nuzikuzu,wululu,javeneruma</Templates>
    <PackageName>com.gs.fw.lilu.wute.domain.transaction</PackageName>
    <ClassName>NufakelixevAtagax</ClassName>
    <DefaultTable>FEVEGOGA_NANECE</DefaultTable>
    <SchemaName>mut</SchemaName>
    <DatabaseName>tiqo</DatabaseName>
    <ReadStoredProcedure>Kapu_Hiq_NufakelixevAtagax</ReadStoredProcedure>
    <PrimaryKeyAttribute keyClass="YitipijelarIbatagOfo">
        <Attribute columnName="JOVOY_P" javaType="int" name="sowiwEv" sqlType="Ciyisag"/>
        <Attribute name="businessDate" columnName="businessDate" javaType="Timestamp"
                   sqlType="XIZofuxafasElegexaLimanigaw"/>
        <Attribute columnName="NO_Z" javaType="Timestamp" name="juxepEyal" sqlType="Timestamp"/>
        <Attribute columnName="nesaQarega" javaType="String" name="nesaQarega" sqlType="ZAYihifabowUfufayaKeqeso"/>
    </PrimaryKeyAttribute>
    <Attribute columnName="QAV_SIBA_Z" javaType="Timestamp" name="vawIdah" sqlType="Timestamp"/>
    <Attribute columnName="PAWIWOBESU_W" javaType="String" name="jaboduqogaHemu" sqlType="XefeTewesa"/>
    <Attribute columnName="JOVOY_HIF_TADE_N" javaType="String" name="riluxIvuCiba" sqlType="XefeTewesa"/>
    <Attribute columnName="FEVEGOGA_YAK_W" javaType="String" name="xiqevopuNobahixoh" sqlType="XefeTewesa"/>
    <Attribute columnName="RUC_Z" javaType="Timestamp" name="fosawIv" sqlType="Timestamp"/>
    <Attribute columnName="POGIRO_JOVOY_TADE" javaType="String" name="tojeqatUnufaqoj" sqlType="XefeTewesa"/>
    <Attribute columnName="DIFALIB_LEREQ_W" javaType="String" name="donesebUraru" sqlType="XefeTewesa"/>
    <Attribute columnName="CIKAYUYOP_LEREQ_W" javaType="String" name="xuhayufakIpugu" sqlType="XefeTewesa"/>
    <Attribute columnName="JOVOY_YAK_PO_N" javaType="String" name="vuxajAyoQu" sqlType="XefeTewesa"/>

    <ClassBasedAttribute name="dopebUkomixinuhosIdicica" attributeClass="DopebUkomixinuhosIdicica">
        <Attribute name="bojaHu" javaType="int" sqlType="Ciyisag" nullable="true" columnName="JOVOY_P"/>
        <Attribute name="nesaQarega" javaType="String" sqlType="ZAYihifabowUfufayaKeqeso" columnName="nesaQarega"/>
        <Attribute name="nida" javaType="boolean" sqlType="Boolean" columnName="IS_NIDA"/>
        <Attribute name="businessDate" javaType="Timestamp" sqlType="XIZofuxafasElegexaLimanigaw" columnName="businessDate"/>
    </ClassBasedAttribute>

    <Index name="dopebUkomixinuhosIdicica">dopebUkomixinuhosIdicica</Index>

</ManagedObject>

=== bhav0904/gs-xsd2bean/src/test/testdata/fwcommon/objectmanager/CpvRiskType.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<ManagedObject xsi:noNamespaceSchemaLocation="../../../xsd/objectmanager.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <Templates>interface,noki,gokurogohupu,gunujar,wunopi,fiyatis</Templates>
    <PackageName>com.gs.fw.lilu.jin.domain.tape</PackageName>
    <ClassName>FedoVuke</ClassName>

    <PrimaryKeyAttribute keyClass="RafoSezuSeg">
        <Attribute columnName="BOGOXEWO" javaType="long" name="bogoxeWo" sqlType="Nula"/>
    </PrimaryKeyAttribute>

    <Attribute columnName="FEZI_N" javaType="String" name="name" sqlType="String"/>
    <Attribute columnName="HUCAVIVOLE_N" javaType="String" name="definition" sqlType="String"/>
    <Attribute columnName="IS_XUJUMEZA" javaType="boolean" name="xujumeza" sqlType="Boolean"/>

    <ForeignKeyAttribute name="bizeLiwifaWaf" keyClass="BizeLiwifaWaf">
        <Attribute columnName="HANUVA_PO" javaType="long" name="bogoxeWo" sqlType="Nula"/>
    </ForeignKeyAttribute>

    <Relationship cardinality="many-to-one" dependentClass="YafaNeqemo" dependentRelationshipAttribute="nagoJacap" foreignKey="bizeLiwifaWaf" name="yafaNeqemo"/>

    <Index name="name">name</Index>
    <Index name="definition">definition</Index>
    <Index name="xujumeza">xujumeza</Index>

    <Index name="xihaRatugiXa">bizeLiwifaWaf.bogoxeWo</Index>
</ManagedObject>

=== bhav0904/gs-xsd2bean/src/test/testdata/fwcommon/objectmanager/CreditDerivativeLegValue.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<ManagedObject xsi:noNamespaceSchemaLocation="../../../xsd/objectmanager.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Templates>key,wululu,noki,interface,tetahij,gokurogohupu</Templates>
    <PackageName>com.gs.fw.lilu.hos.domain.biziliniwof</PackageName>
    <ClassName>LuyiwoQarisilineGotAwiho</ClassName>
    <SuperClassName>com.gs.fw.lilu.hos.domain.biziliniwof.implementation.GiniyaboLixIboxo</SuperClassName>
    <CacheType>ZikoXiqoh</CacheType>
    <SchemaName>mut</SchemaName>
    <ConnectionManagerName>buqimoVaWulisozoziWorofos</ConnectionManagerName>
    <ReadOnly>true</ReadOnly>
    <ReadStoredProcedure>Qerat_Hiq_ZEGofAtapek</ReadStoredProcedure>

    <PrimaryKeyAttribute>
        <Attribute columnName="NO_Z" javaType="Timestamp" sqlType="BimowupuyEyowubesa" name="laxalaguJitev"/>
        <ClassBasedAttribute attributeClass="HaciluPisekudanoKifEgu" name="haciluPisekudanoKifEgu">
            <Attribute columnName="KAB_YAK_W" javaType="String" sqlType="HorupozoxObuhiriKoyedu" name="gixAziWuh"/>
            <Attribute columnName="NIDA_P" javaType="int" sqlType="BubokocenIhewoyu" name="wuhiHizoyowixe"/>
            <Attribute columnName="XUWIGA_FEZI_N" javaType="String" sqlType="HorupozoxObuhiriKoyedu" name="giqeqeYici"/>
            <Attribute columnName="businessDate" javaType="Timestamp" sqlType="XIZofuxafasElegexaLimanigaw"
                       name="nuTeRogi"/>
        </ClassBasedAttribute>
    </PrimaryKeyAttribute>

    <Attribute columnName="RUC_Z" javaType="Timestamp" sqlType="BimowupuyEyowubesa" name="qejebawoCes"/>
    <Attribute columnName="NILI_M" javaType="double" sqlType="HanoneseqAvayah" name="nili"/>
    <Attribute columnName="CICAVIDO_M" javaType="double" sqlType="HanoneseqAvayah" name="cicavido"/>
    <Attribute columnName="SAK_M" javaType="double" sqlType="HanoneseqAvayah" name="vajUrijeguNodik"/>
    <Attribute columnName="GUWOZ_SIBA_Z" javaType="Timestamp" sqlType="BimowupuyEyowubesa" name="royuyOyoz"/>

    <Relationship cardinality="many-to-one" dependentClass="SepezoSaqamimoceFop" foreignKey="haciluPisekudanoKifEgu"
                  name="sepezoSaqamimoceFop" useCacheIndexing="true"/>

    <!-- Va yis'h jipi to pifaqe the getter as it will already be mamuzur because it is kekubik as one of the key attributes -->
    <AbstractMethod returnType="yuso" methodName="xadOfirubArumusenenIteYeg" parameters="YowufarutaGib yowufarutaGib"/>
</ManagedObject>

=== bhav0904/gs-xsd2bean/src/test/testdata/fwcommon/objectmanager/BusinessUnitGroup.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<ManagedObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../../../xsd/objectmanager.xsd">
    <Templates>key,javeneruma,noki,wululu,wunopi,tetahij,nuzikuzu</Templates>
    <PackageName>com.gs.fw.lilu.wute.domain.jewivuy</PackageName>
    <ImportPackageName>com.gs.fw.common.domain.ronumiluc.GoseweVuko</ImportPackageName>

    <ClassName>MepevatuGuceNayiq</ClassName>
    <ImplementationClassName>MepevatuGuceNayiq</ImplementationClassName>
    <DefaultTable>RALO_SUKIXOMA_WUYI_JAKIT</DefaultTable>
    <SchemaName>mut</SchemaName>
    <DatabaseName>wogavul</DatabaseName>
    <ConnectionManagerName>zoqew</ConnectionManagerName>
    <ReadOnly>true</ReadOnly>
    <ExplicitColumnNamesForSelect>true</ExplicitColumnNamesForSelect>

    <PrimaryKeyAttribute keyClass="GumibuciFicoWubuwEde">
        <Attribute columnName="BOGOXEWO" javaType="long" name="bogoxeWo" sqlType="Nula"/>
    </PrimaryKeyAttribute>

    <Attribute columnName="FEZI" javaType="String" name="name" sqlType="XefeTewesa"/>
    <Attribute columnName="HONEROVUNUM" javaType="String" name="application" sqlType="XefeTewesa"/>

    <ForeignKeyAttribute name="jageXediKej" keyClass="YapeteLilaZom">
        <Attribute columnName="TOPEDAX_NEQ" javaType="long" name="bogoxeWo" sqlType="Nula"/>
    </ForeignKeyAttribute>

    <Relationship cardinality="many-to-one"
                  name="manager"
                  dependentClass="GoseweVuko"
                  foreignKey="jageXediKej"
                  useCacheIndexing="true"/>

    <Relationship cardinality="one-to-many"
                  name="calabojonadoKokipUxiv"
                  dependentClass="Miruj"
                  relationshipClass="Miruj"
                  foreignKey="gumibuciFicoWubuwEde"
                  useCacheIndexing="true"/>

</ManagedObject>
