=== bhav0904/gs-xsd2bean/src/test/xsd/parserconfig.xsd
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="FlatFileParserConfig">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Header" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:attribute name="required" type="xsd:boolean" use="required"/>
                        <xsd:attribute name="identifier" type="xsd:string" use="optional"/>
                        <xsd:attribute name="dateRegex" type="xsd:string" use="optional"/>
                        <xsd:attribute name="dateFormat" type="xsd:string" use="optional"/>
                        <xsd:attribute name="simpleFormat" type="xsd:string" use="optional"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Trailer" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:attribute name="required" type="xsd:boolean" use="required"/>
                        <xsd:attribute name="identifier" type="xsd:string" use="optional"/>
                        <xsd:attribute name="trailerCountRegex" type="xsd:string" use="optional"/>
                        <xsd:attribute name="trailerCountOffset" type="xsd:int" use="optional"/>
                        <xsd:attribute name="simpleFormat" type="xsd:string" use="optional"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Mapping" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:attribute name="attribute" type="xsd:string" use="required"/>
                        <xsd:attribute name="position" type="xsd:int" use="required"/>
                        <xsd:attribute name="format" type="xsd:string" use="optional"/>
                        <xsd:attribute name="nullable" type="xsd:boolean" use="optional"/>
                        <xsd:attribute name="trim" type="xsd:boolean" use="optional"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="MapWithKey" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:attribute name="method" type="xsd:string" use="required"/>
                        <xsd:attribute name="key" type="xsd:string" use="required"/>
                        <xsd:attribute name="position" type="xsd:int" use="required"/>
                        <xsd:attribute name="keyFactory" type="xsd:string" use="required"/>
                        <xsd:attribute name="nullable" type="xsd:boolean" use="optional"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="KeyValueMapping" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:attribute name="attribute" type="xsd:string" use="required"/>
                        <xsd:attribute name="key" type="xsd:string" use="required"/>
                        <xsd:attribute name="format" type="xsd:string" use="optional"/>
                        <xsd:attribute name="nullable" type="xsd:boolean" use="optional"/>
                        <xsd:attribute name="trim" type="xsd:boolean" use="optional"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="FixedValue" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:attribute name="attribute" type="xsd:string" use="required"/>
                        <xsd:attribute name="value" type="xsd:string" use="required"/>
                        <xsd:attribute name="format" type="xsd:string" use="optional"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="FixedColumnMapping" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:attribute name="attribute" type="xsd:string" use="required"/>
                        <xsd:attribute name="startPosition" type="xsd:int" use="required"/>
                        <xsd:attribute name="length" type="xsd:int" use="required"/>
                        <xsd:attribute name="format" type="xsd:string" use="optional"/>
                        <xsd:attribute name="nullable" type="xsd:boolean" use="optional"/>
                        <xsd:attribute name="trim" type="xsd:boolean" use="optional"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="delimiter" type="xsd:string" use="required"/>
            <xsd:attribute name="sectionQuotingEnabled" type="xsd:boolean" use="optional" default="true">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="keyDelimiter" type="xsd:string" use="optional"/>
            <xsd:attribute name="inflatedObject" type="xsd:string" use="required"/>
            <xsd:attribute name="parserErrorHandler" type="xsd:string" use="optional"/>
            <xsd:attribute name="columns" type="xsd:int" use="optional"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== bhav0904/gs-xsd2bean/src/test/testdata/flatfileparser/FundingStockLoansCarryFileParser.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<FlatFileParserConfig
        delimiter="~"
        inflatedObject="com.gs.fw.para.domain.qaje.position.implementation.ZizasirEheseJosucacuRepi"
        columns="10"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../xsd/parserconfig.xsd">
	<Header required="true" identifier="NASAVU:" simpleFormat="NASAVU:[hojakinipo]*FUZASINADU:[hojakinipo][kufuXEri][hojakinipo]"/>
	<Trailer required="true" identifier="KABANAS:" simpleFormat="KABANAS:[hojakinipo][count]*" trailerCountOffset="-2"/>

    <Mapping attribute="cejasawUwesij"  position="1" trim="true"/>
    <Mapping attribute="zasomurOrefi"   position="2" trim="true"/>
    <Mapping attribute="fujawuQoyoto"   position="3" nullable="true" trim="true"/>

    <MapWithKey method="jiyApirumAguxebi" key="bekeluwaYozi"        position="4" keyFactory="com.gs.fw.para.rehepiyebag.qayamudoz.yatuy.SunipAlalApugaRiriyik"/>
    <MapWithKey method="jiyApirumAguxebi" key="joluZoxo"            position="5" keyFactory="com.gs.fw.para.rehepiyebag.qayamudoz.yatuy.SunipAlalApugaRiriyik"/>
    <MapWithKey method="jiyApirumAguxebi" key="jozuseKisePimeYuha"  position="6" keyFactory="com.gs.fw.para.rehepiyebag.qayamudoz.yatuy.SunipAlalApugaRiriyik"/>
    <MapWithKey method="jiyApirumAguxebi" key="yiyeveLoyeFahoJiho"  position="7" keyFactory="com.gs.fw.para.rehepiyebag.qayamudoz.yatuy.SunipAlalApugaRiriyik"/>
    <MapWithKey method="jiyApirumAguxebi" key="yoliQanuReki"        position="8" keyFactory="com.gs.fw.para.rehepiyebag.qayamudoz.yatuy.SunipAlalApugaRiriyik"/>
    <MapWithKey method="jiyApirumAguxebi" key="mequQivoYidiWuha"    position="9" keyFactory="com.gs.fw.para.rehepiyebag.qayamudoz.yatuy.SunipAlalApugaRiriyik"/>
    <MapWithKey method="jiyApirumAguxebi" key="vecaBiluWediJulu"    position="10" keyFactory="com.gs.fw.para.rehepiyebag.qayamudoz.yatuy.SunipAlalApugaRiriyik"/>

</FlatFileParserConfig>

=== bhav0904/gs-xsd2bean/src/test/testdata/flatfileparser/cswAsOfFeedConfig.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<FlatFileParserConfig
        delimiter="|"
        inflatedObject="com.gs.fw.para.application.tekihif.dazi.jewivuy.tarani.XISUrawOpawoz"
        columns="24"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../xsd/parserconfig.xsd">
    <Header required="true" identifier="***KIKU|" simpleFormat="***KIKU|*|businessDate=[kufuXEri]|*"/>
    <Trailer required="false" identifier="***REMI" simpleFormat="***REMI|*|sitemeqAmulu=[count]"/>

    <Mapping attribute="date"                position="1"    trim="true"/>
    <Mapping attribute="rivusujAr"              position="3"    trim="true"/>
    <Mapping attribute="cejasawUwesij"          position="4"    trim="true"/>
    <Mapping attribute="bihirovEtaq"            position="5"    trim="true"/>
    <Mapping attribute="suvufObub"              position="6"    trim="true"/>
    <Mapping attribute="vawIdah"                position="7"    trim="true"/>
    <Mapping attribute="wivUhu"                 position="11"    trim="true"/>
    <Mapping attribute="yeyUvUji"               position="16"   trim="true"/>
   

</FlatFileParserConfig>

=== bhav0904/gs-xsd2bean/src/test/testdata/flatfileparser/FundingStockLoansFileParser.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<FlatFileParserConfig
        delimiter="|"
        inflatedObject="com.gs.fw.para.domain.transaction.implementation.RonezuwAfidiKucosOxubutuxuqoYoqa"
        columns="43"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../xsd/parserconfig.xsd">
	<Header required="true" identifier="NASAVU:" simpleFormat="NASAVU:[hojakinipo]*FUZASINADU:[hojakinipo][yyyy/WE/dd]"/>
	<Trailer required="true" identifier="KABANAS" simpleFormat="KABANAS[hojakinipo][count]*"/>

    <Mapping attribute="hehiDeti" position="1"  />
    <Mapping attribute="yizeyuKo" position="2" nullable="true" />
    <Mapping attribute="mohobaniPow" position="3"  />
    <Mapping attribute="degunifaKazo" position="4" nullable="true" />
    <Mapping attribute="lomoh" position="5" nullable="true" />
    <Mapping attribute="big" position="6" nullable="true" />
    <Mapping attribute="nosujabiTesi" position="7" nullable="true" />
    <Mapping attribute="qazebaguPegi" position="8" nullable="true" />
    <Mapping attribute="vawIdah" position="9" nullable="true" />
    <Mapping attribute="moCeze" position="10" nullable="true" />
    <Mapping attribute="nejapulageDavo" position="11" nullable="true" />
    <Mapping attribute="purpose" position="12" nullable="true" />
    <Mapping attribute="fujawuQoyoto" position="13" nullable="true" />
    <Mapping attribute="kiwIzam" position="14" nullable="true" />
    <Mapping attribute="tujoXuk" position="15" nullable="true" />
    <Mapping attribute="pajUrog" position="16" nullable="true" />
    <Mapping attribute="vojitomuXodimu" position="17" nullable="true" />
    <Mapping attribute="wutuhagiDelataJale" position="18" nullable="true" />
    <Mapping attribute="qonaximoFudomo" position="19" nullable="true" />
    <Mapping attribute="vazubosaYuz" position="20" nullable="true" />
    <Mapping attribute="qulamupedIrifadaz" position="21" nullable="true" />
    <Mapping attribute="pebajefoLocop" position="22" nullable="true" />
    <Mapping attribute="pamina" position="23" nullable="true" />
    <Mapping attribute="keriqeWadov" position="24" nullable="true" />
    <Mapping attribute="tofuveLedevUju" position="25" nullable="true" />
    <Mapping attribute="coputiguZiMihi" position="26" nullable="true" />
    <Mapping attribute="konasoHuNibi" position="27" nullable="true" />
    <Mapping attribute="dinimeyOziz" position="28" nullable="true" />
    <Mapping attribute="hewiyinoNizu" position="29" nullable="true" />
    <Mapping attribute="gisiGura" position="30" nullable="true" />
    <Mapping attribute="lavaxAdenigoBa" position="31" nullable="true" />
    <Mapping attribute="wukereleRegi" position="32" nullable="true" />
    <Mapping attribute="xakude" position="33" nullable="true" />
    <Mapping attribute="gulufOnif" position="34" nullable="true" />
    <Mapping attribute="kegofusucEcivaciJog" position="35" nullable="true" />
    <Mapping attribute="qorawe" position="36" nullable="true" />
    <Mapping attribute="wahaluweJosey" position="37" nullable="true" />
    <Mapping attribute="cuzuqefusuRuhi" position="38" nullable="true" />
    <Mapping attribute="dogujAbus" position="39" nullable="true" />
    <Mapping attribute="rewAlexobugecOxuz" position="40" nullable="true" />
    <Mapping attribute="matUxakeHuxa" position="41" nullable="true" />
    <Mapping attribute="bihirovEtaq" position="42" nullable="true" />
    <Mapping attribute="vesudabOlori" position="43" nullable="true" />

</FlatFileParserConfig>

=== bhav0904/gs-xsd2bean/src/test/testdata/flatfileparser/GmiCommissionsAggregateFileParser.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<FlatFileParserConfig
        delimiter=""
        inflatedObject="com.gs.fw.para.domain.juk.panixopuyor.VisOposequlameMasativinIdohEbuq"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../xsd/parserconfig.xsd">

    <Header required="false" identifier="NASAVU:" />
    <Trailer required="false" identifier="KABANAS:" />
    <FixedColumnMapping attribute="RiquXadonaz" startPosition="0" length="10" trim="true"/>
    <FixedColumnMapping attribute="MihihunApiv" startPosition="11" length="2" trim="true"/>
    <FixedColumnMapping attribute="BunirodAlidev" startPosition="14" length="6" trim="true"/>
    <FixedColumnMapping attribute="LavEloc" startPosition="21" length="1" trim="true" />
    <FixedColumnMapping attribute="XajezanIcayev" startPosition="23" length="15" trim="true"/>
    <FixedColumnMapping attribute="YoqakiDamo" startPosition="39" length="6" trim="true"/>
    <FixedColumnMapping attribute="CefugaroVuze" startPosition="46" length="3" trim="true"/>
    <FixedColumnMapping attribute="WizesoyeDode" startPosition="50" length="2" trim="true"/>
    <FixedColumnMapping attribute="JamakElemAmihif" startPosition="53" length="8" trim="true" />
    <FixedColumnMapping attribute="WafumaSihuXoyexa" startPosition="62" length="8" trim="true" />
    <FixedColumnMapping attribute="NavUcahu" startPosition="71" length="12" trim="true" />
    <FixedColumnMapping attribute="FurInasesu" startPosition="84" length="8" trim="true"/>
    <FixedColumnMapping attribute="ZeqimUfesob" startPosition="93" length="1" trim="true" />
</FlatFileParserConfig>

=== bhav0904/gs-xsd2bean/src/test/testdata/flatfileparser/PwmCommissionsFileParser.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<FlatFileParserConfig
        delimiter="|"
        inflatedObject="com.gs.fw.para.domain.transaction.implementation.FanuleliyiWuvaqotaroy"
        columns="26"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../xsd/parserconfig.xsd">

    <Header required="true" identifier="NASAVU:" simpleFormat="NASAVU:*[yyyy/WE/dd]"/>
    <Trailer required="true" identifier="KABANAS:" simpleFormat="KABANAS:[hojakinipo][count]*" trailerCountOffset="-2"/>

    <!--<Mapping attribute="lijebeSudume" position="1"/>-->
    <Mapping attribute="wileNihiQuvEgunid" position="2"/>
    <Mapping attribute="rapajAfep" position="3"/>
    <Mapping attribute="niqivUdoc" position="4"/>
    <Mapping attribute="prod" position="5"/>
    <Mapping attribute="xicemEniLoyi" position="7"/>
    <Mapping attribute="xalugiyOmipAcuxem" position="9"/>
    <Mapping attribute="nixotadeBovupanAs" position="12" nullable = "true"/>
    <Mapping attribute="zevupadeTuciTohadiqeRogufo" position="13"/>
    <Mapping attribute="yaheyiXexomeBaqafa" position="14"/>
    <Mapping attribute="weleLomeriqoceTejomiDubodo" position="15"/>
    <Mapping attribute="zoJira" position="16"/>
    <Mapping attribute="miluYesevOki" position="17"/>
    <Mapping attribute="mujiDuzafiziBimiki" position="20"/>
    <Mapping attribute="jamakElemAmihif" position="21"/>
    <Mapping attribute="raxokaCeyubupa" position="22"/>
    <Mapping attribute="wafumaSihuXoyexa" position="25"/>
    <FixedValue attribute="xonapoqoyitAgujAtaYudiko" value="FOGULI"/>
    <FixedValue attribute="sopUmufad"                value="0.0"/>
    <FixedValue attribute="nivuWevanigAkahug"        value=""/>
    <FixedValue attribute="yuzewUji"                 value=""/>
    <FixedValue attribute="boveBaruSelegusor"        value=""/>
    <FixedValue attribute="wokuJaso"                 value=""/>
</FlatFileParserConfig>

=== bhav0904/gs-xsd2bean/src/test/testdata/flatfileparser/LoanRangerFundingFactorFileParser.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<FlatFileParserConfig
        delimiter=","
        inflatedObject="com.gs.fw.para.domain.transaction.implementation.YoweJaxaqePuvamikafeFenihajIyuhumItubelojivo"
        columns="7"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../xsd/parserconfig.xsd">
	<Header required="true" identifier="PET" simpleFormat="PET: [kufuXEri]*"/>
	<Trailer required="true" identifier="KABANAS" simpleFormat="KABANAS:[hojakinipo][count]"/>

	<Mapping attribute="rivusujAr9Dufij"	position="1"    trim="true"/>
    <Mapping attribute="puvewUx"		    position="2"    trim="true"/>
    <Mapping attribute="suvufObub"	        position="3"    trim="true" format="kufuXEri"/>
    <Mapping attribute="vawIdah"	        position="4"    trim="true" format="kufuXEri"/>
    <Mapping attribute="wulolozuniWoyolo"   position="5"    trim="true"/>
    <Mapping attribute="mexiceKidule"       position="6"    trim="true"/>
    <Mapping attribute="tuyahigOfokit"      position="7"    trim="true"/>
</FlatFileParserConfig>

=== bhav0904/gs-xsd2bean/src/test/testdata/flatfileparser/GSAM_CustomerFileParser.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<FlatFileParserConfig delimiter="|"
                      inflatedObject="com.gs.fw.para.vala.domain.transaction.implementation.GamiSatakuqoMoricivehac"
                      columns="39"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:noNamespaceSchemaLocation="../../xsd/parserconfig.xsd">

    <Header required="true" identifier="ZON"
            simpleFormat="ZON|[WE/dd/yyyy]"/>
    <Trailer required="true" identifier="KEJ" simpleFormat="KEJ|[count]"/>

    <Mapping attribute="fijeJi" position="2" nullable="false"/>
    <Mapping attribute="degunifaKazo" position="3" nullable="false"/>
    <Mapping attribute="sopoje" position="5" nullable="true"/>
    <Mapping attribute="noyuge" position="6" nullable="true"/>

    <Mapping attribute="tAmulufa" position="9" nullable="true"/>
    <Mapping attribute="strategy" position="10" nullable="true"/>
    <Mapping attribute="camorEdoca" position="11" nullable="true"/>
    <Mapping attribute="pecOtoratu" position="12" nullable="true"/>
    <Mapping attribute="wupigaqapuMijizop" position="13" nullable="true"/>
    <Mapping attribute="nuZimovuku" position="14" nullable="true"/>
    <Mapping attribute="yiWoyeha" position="15" nullable="true"/>
    <Mapping attribute="nibekupumAwonevi" position="16" nullable="true"/>
    <Mapping attribute="giqulicefIcagiluz" position="18" nullable="true"/>
    <Mapping attribute="cigOxiwuxaJepi" position="19" nullable="true"/>
    <Mapping attribute="nasIjAlas" position="22" nullable="true"/>
    <Mapping attribute="yecaDufokedoFeqege" position="27" nullable="true"/>
    <Mapping attribute="ceKoholu" position="28" nullable="true"/>
    <Mapping attribute="guyuliRoxebobi" position="29" nullable="true"/>
    <Mapping attribute="rifufaVokamep" position="30" nullable="true"/>
    <Mapping attribute="qitoliqiwAxit" position="38" nullable="true"/>
    <Mapping attribute="lapupeDino" position="39" nullable="true"/>
</FlatFileParserConfig>

=== bhav0904/gs-xsd2bean/src/test/testdata/flatfileparser/MbdInvestmentLoaderFileParser.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<FlatFileParserConfig 
        delimiter="|"
        inflatedObject="com.gs.fw.para.fufexoze.wuhoticuhomec.RenEmilakayuw"
        columns="8"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../xsd/parserconfig.xsd">
    <Header required="true" identifier="NASAVU:"/>
	<Trailer required="true" identifier="KABANAS:"/>

	<Mapping attribute="temEdot" position="1"/>
    <Mapping attribute="riqaBiyo1" position="2"/>
	<Mapping attribute="bukufiCu" position="3"/>
    <Mapping attribute="lehopiRovo" position="4"/>
    <Mapping attribute="pujiJutimose" position="5"/>
	<Mapping attribute="riqaBiyo4" position="6"/>
    <Mapping attribute="riqaBiyo3" position="7" />
    <Mapping attribute="riqaBiyo2" position="8"/>

</FlatFileParserConfig>
