=== bhav0904/gs-xsd2bean/src/test/xsd/wireobject.xsd
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
            jxb:version="1.0">
    <xsd:annotation>
        <xsd:documentation xml:lang="en">
            Lorem ipsum dolor sit amet
        </xsd:documentation>
        <xsd:appinfo>
            <jxb:globalBindings generateIsSetMethod="true"/>
        </xsd:appinfo>
    </xsd:annotation>

    <xsd:element name="WireObject" type="WireObjectType"/>

    <xsd:complexType name="WireObjectType">
        <xsd:complexContent>
            <xsd:extension base="WireObjectInfoType">
                <xsd:sequence>
                    <xsd:element name="Version" type="VersionType" minOccurs="1" maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="WireObjectInfoType" >
        <xsd:attribute name="name" use="required">
            <xsd:simpleType>
              <xsd:restriction base = "xsd:string">
                <xsd:pattern value = "[_a-zA-Z]+"/>
              </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="package" type="javaPath" use="required"/>
        <xsd:attribute name="superclass" type="javaPath" default="com.gs.fw.common.base.wire.AbstractWireObject"/>
    </xsd:complexType>

    <xsd:complexType name="VersionType">
        <xsd:sequence>
            <xsd:element name="Attribute" type="AttributeType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="AttributeType">
        <xsd:attribute name="name" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="[a-z][a-z0-9A-Z]*"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="type">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="short" />
                    <xsd:enumeration value="boolean"/>
                    <xsd:enumeration value="byte"/>
                    <xsd:enumeration value="char"/>
                    <xsd:enumeration value="int"/>
                    <xsd:enumeration value="float"/>
                    <xsd:enumeration value="double"/>
                    <xsd:enumeration value="long"/>
                    <xsd:enumeration value="String"/>
                    <xsd:enumeration value="Timestamp"/>
                    <xsd:enumeration value="Date"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="className" type="javaPath"/>
        <xsd:attribute name="generic" type="javaPath"/>
        <xsd:attribute name="defaultValue" type="xsd:token" />
        <xsd:attribute name="timestampType" type="timestampRule" />
        <xsd:attribute name="deleted" type="xsd:boolean" />
        <xsd:attribute name="nullable" type="xsd:boolean" default="false"/>
        <xsd:attribute name="pooled" type="xsd:boolean" default="false"/>
        <xsd:attribute name="infinityTime" type="xsd:token" />
        <xsd:attribute name="maxLength">
            <xsd:simpleType>
              <xsd:restriction base = "xsd:string">
                <xsd:pattern value = "[0-9]+"/>
              </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:simpleType name="timestampRule" >
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="timezoneSensitive" />
            <xsd:enumeration value="timezoneSensitiveWithInfinity" />
            <xsd:enumeration value="timezoneInsensitive" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="javaPath">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[a-zA-Z][a-z0-9A-Z\.]*"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== bhav0904/gs-xsd2bean/src/test/testdata/wireobject/ContractDetailWireObject.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<WireObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../../xsd/wireobject.xsd"
            name="YedunohoCazeciZeviRikeja"
            package="com.gs.fw.para.domain.transaction.implementation">

    <Version>

        <Attribute name="xel" type="String" maxLength="30"/>
        <Attribute name="sekAfItuzojiVo" type="String" maxLength="40"/>
        <Attribute name="bujipahaFemu" type="String" maxLength="32"/>
        <Attribute name="ruloXajUpivuQojUg" type="String" maxLength="30"/>
        <Attribute name="qurIbatOgihasazi" type="String" maxLength="1"/>
        <Attribute name="dimubukEceJohaXeququhaz" type="String" maxLength="1"/>
        <Attribute name="lutihaHuqug" type="String" maxLength="1"/>
        <Attribute name="pociheteroLaviziyOzig" type="String" maxLength="1"/>
        <Attribute name="gucucuDikiwelix" type="String" maxLength="1"/>
        <Attribute name="deyofajofuGomehadIzidoke" type="String" maxLength="3"/>
        <Attribute name="biserenezaLuramujUvohi" type="String" maxLength="31"/>
        <Attribute name="ginunudabeXuviricazAxowewi" type="String" maxLength="3"/>
        <Attribute name="mamEhiXukodexa" type="String" maxLength="3"/>
        <Attribute name="cikaYonufevoPegoqohoh" type="String" maxLength="1"/>
        <Attribute name="kavahiGu" type="String" maxLength="41"/>
        <Attribute name="vagujAjaq" type="String" maxLength="32"/>
        <Attribute name="vixakiLuto" type="String" maxLength="32"/>
        <Attribute name="hikewusuNuvi" type="String" maxLength="32"/>
        <Attribute name="qomodobAgisAjoqevu" type="String" maxLength="15"/>
        <Attribute name="waxetiHoxexOfib" type="String" maxLength="7"/>
        <Attribute name="ziranuJupimeled" type="String" maxLength="1"/>
        <Attribute name="buLesimafog" type="String" maxLength="1"/>
        <Attribute name="cizalegAquXihuXomuTiSivowe" type="String" maxLength="1"/>
        <Attribute name="kiqinayEveci" type="String" maxLength="32"/>
        <Attribute name="mupikunIwuj" type="String" maxLength="8"/>
        <Attribute name="jatokebodeLako" type="String" maxLength="32"/>
        <Attribute name="sewetoBamuruBuquhita" type="String" maxLength="31"/>
        <Attribute name="hijuguVedetumoNidi" type="String" maxLength="32"/>
        <Attribute name="bohOfefEz" type="String" maxLength="32"/>
        <Attribute name="josonica" type="double"/>
        <Attribute name="gozapimiciPalaxanAvuzaf" type="double"/>
        <Attribute name="wimutototuGubugiqamAvapiy" type="double"/>
        <Attribute name="gucAqaQiniji" type="double"/>
        <Attribute name="gucotijoLiwig" type="double"/>
        <Attribute name="tinitiJuqux" type="double"/>
        <Attribute name="vugacokeMeyobuyu" type="double"/>
        <Attribute name="cajoyivEvitoheqOfinofoj" type="double"/>
        <Attribute name="ziposetozIy" type="String" maxLength="30"/>
        <Attribute name="fazeqeNuzi" type="Timestamp"/>
        <Attribute name="vawIdah" type="Timestamp"/>
        <Attribute name="felotAtakehaMa" type="String" maxLength="32"/>
        <Attribute name="yidifUnonigel" type="double"/>
        <Attribute name="putasaKiga" type="String" maxLength="30"/>
        <Attribute name="hijezoZanime" type="String" maxLength="31"/>

    </Version>

    <Version>
        <Attribute name="rawiqonOkagaqaxOwujetiz" type="String" maxLength="3"/>
    </Version>

    <Version>
        <Attribute name="wigehikImozozexOvenugeg" type="String" maxLength="3"/>
    </Version>

</WireObject>

=== bhav0904/gs-xsd2bean/src/test/testdata/wireobject/SwapUnderlierWireObject.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<WireObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../../xsd/wireobject.xsd"
            name="HaxeKavogurimEwod" package="com.gs.fw.para.domain.nida.implementation">
<Version>
    <Attribute name="minedurokIs" type="String"/>
    <Attribute name="siqupiXife" type="String"/>
    <Attribute name="hequdeDo" type="int"/>
    <Attribute name="sibewUs" type="int"/>
    <Attribute name="wuyi" type="double"/>
    <Attribute name="hosAj" type="String"/>
    <Attribute name="big" type="String"/>
    <Attribute name="rot" type="String"/>
    <Attribute name="haxocuquTadut" type="double"/>
    <Attribute name="jiculujawIba" type="String"/>
    <Attribute name="hubuhomayEwiyu" type="double"/>
    <Attribute name="heciXitiKos" type="double" />
    <Attribute name="wotIjaruQit" type="double" />
    <Attribute name="verAnifoZav" type="String" />
    <Attribute name="tukawebaHoqigi" type="String" />
    <Attribute name="higevixomobuZup" type="String"/>

    <!-- Cami MapAfikexatexaRinehig -->
    <Attribute name="kepiTe" type="int"/>
    <Attribute name="yikiveKu" type="String"/>
    <Attribute name="cavAvorerIz" type="String" />
    <Attribute name="livaFulubak" type="String"/>
</Version>
</WireObject>

=== bhav0904/gs-xsd2bean/src/test/testdata/wireobject/CarryListedDerivativeWireObject.xml
<!--
Copyright 2016 Goldman Sachs.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<WireObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../../xsd/wireobject.xsd"
            name="BavivUcofocUpupumakozEjalEnijub" package="com.gs.fw.para.bapeyisevibo.data">
    <Version>
        <Attribute name="qazewotEsa" type="String" maxLength="10"/>
        <Attribute name="big" type="String" nullable="false" maxLength="15"/>
        <Attribute name="kocinIyiq" type="String" nullable="false" maxLength="5"/>

        <Attribute name="xevezEdopa" type="double" nullable="false"/>
        <Attribute name="josonica" type="double" nullable="false"/>
    </Version>
    <Version>
       <Attribute name="cilewezuNigado" type="String" nullable="false"/>    
    </Version>
</WireObject>
